name: ingatlan_scraper_dart
private: True
version: 0.0.1
description: Ingatlan.com scraper
author: blas3nik

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  html: ^0.13.3+3
  queries: ^0.1.14
  gsheets: ^0.2.4
  stats: ^1.0.0
  shelf: ^0.7.3
  aqueduct: ^4.0.0-b1